## Algebra liniowa - biblioteki numeryczne

W środowisku języka Python dostępne są dwie biblioteki numeryczne numpy i scipy. Dokumentacja: https://numpy.org/doc/, https://docs.scipy.org/doc/. Znajdź informacje wyjaśniające różnice między tymi bibliotekami.

Pakiet NumPy (Numeric Python) zaweria podstawowe procedury do obsługi dużych tablic oraz macierzy danych numerycznych. Pakiet SciPy (Scientific Python) rozszerza funkcjonalność NumPy'a o bogatą kolekcję algorytmów służących do optymalizacji, minimalizacji, regresji, transformaty Fouriera, algebry liniowej oraz wielu innych używanych w nauce, inżynierii.


### Zadanie 1
Napisz krótki program, który wyświetli informację o wersji biblioteki oraz jej konfiguracji. Zwróć uwagę z jakich bibliotek numerycznych korzystają biblioteki Python'a.

Warty odnotowania jest fakt, że biblioteki zazwyczaj są zaimplementowane w C, jednak u mu mnie były one w f77 (FORTRAN 77). 

In [8]:
import numpy as np


print("NumPy version:", np.__version__)
print(np.__config__.show())


NumPy version: 1.18.1
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


In [2]:
import scipy as sc


print("SciPy version:", sc.__version__)
print("NumPy version used in SciPy:", sc.__numpy_version__)
print(sc.__config__.show())


SciPy version: 1.4.1
NumPy version used in SciPy: 1.18.1
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['C:\\projects\\scipy-wheels\\scipy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['C:\\projects\\scipy-wheels\\scipy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\scipy-wheels\\scipy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:\\projects\\scipy-wheels\\scipy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


Obie biblioteki korzystają z otwartoźródłowej implementacji biblioteki BLAS (Basic Linear Algebra Subprograms), służącej do optymalizacji operacji w zalezności od platformy sprzętowej.

### Zadanie 2
Napisz program, który wyświetla wbudowaną pomoc dla funkcji: dodawanie wektorów.

In [9]:
import numpy as np


print(np.info(np.add))
# or
print(np.add.__doc__) 
# or
print(help(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

### Zadanie 3
Napisz programy, które testują wektory danych pod kątem obecności elementów zerowych lub nieskończonych (sprawdź różne warianty takich funkcji). Napisz program porównujący wektory i macierze (według wartości elementów).

In [10]:
import numpy as np


def has_zero(v):
    print("Zero at:", np.where(v == 0))


def has_inf(v):
    print("inf at:", np.where(v == np.inf))
    print("-inf at:", np.where(v == -np.inf))


def are_equal(a, b):
    if a.ndim == b.ndim and a.size == b.size:
        return a == b
    elif a.size > b.size:
        b = np.resize(b, (1, a.size))
        a = np.resize(a, (1, a.size))
        return a == b
    else:
        a = np.resize(b, (1, b.size))
        b = np.resize(b, (1, b.size))
        return a == b


a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 2, 5])
print(are_equal(a, b))

c = np.array([[1, 2], [3, 4]])
d = np.mat(c)
print(are_equal(d, a))

has_zero(np.array([0, 1, 1]))
has_inf(np.array([np.inf, 1, 1, -np.inf]))

[[ True  True False False False]]
[[ True  True  True  True  True]]
Zero at: (array([0], dtype=int32),)
inf at: (array([0], dtype=int32),)
-inf at: (array([3], dtype=int32),)


### Zadanie 4 
Napisz program, który wylicza ile danych w bajtach zajmuje wektor lub macierz

In [3]:
import numpy as np


def show_bytes(tab):
    if not isinstance(tab, np.ndarray) and not isinstance(tab, np.matrix):
        tab = np.array(tab)

    return tab.nbytes


a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = [[1, 2, 3], [4, 5, 6]]
m = np.mat(b)
print(show_bytes(a))
print(show_bytes(b))
print(show_bytes(m))

24
24
24


### Zadanie 5
Napisz kilka programów, które demonstrują jak można w numpy tworzyć wektory i macierze wypełnione różnymi danymi lub mającymi pewną szczególną postać, np. , danymi losowymi, danymi z podanego zakresy, macierze identyczności, ... 

In [11]:
import numpy as np

print("Matrix 3x4 filled with 0's:")
print(np.zeros((3, 4)), "\n")

print("Matrix 2x6 filled with 1's:")
print(np.ones((2, 6)), "\n")

print("Matrix 4x4 filled with any number (eg. 9's):")
print(np.full((4, 4), 9), "\n")

print("Identity matrix 5x5:")
print(np.identity(5), "\n")

print("Matrix 3x5 filled with random numbers from range [-5, 5]")
A = np.random.randint(-5, 5, size=(3, 5))
print(A, "\n")

print("Evenly spaced values within a given interval:")
print(np.arange(0., 4.5, 0.5),  "\n")

Matrix 3x4 filled with 0's:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

Matrix 2x6 filled with 1's:
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]] 

Matrix 4x4 filled with any number (eg. 9's):
[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]] 

Identity matrix 5x5:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 

Matrix 3x5 filled with random numbers from range [-5, 5]
[[ 2 -5 -3  2 -3]
 [-2  2 -3  4  3]
 [ 1 -1  4 -2  4]] 

Evenly spaced values within a given interval:
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4. ] 



### Zadania 6
Napisz programy wykonujące podstawowe operacje algebry: dodawanie wektorów, mnożenie wektorów, mnożenie macierzy. Najpierw napisz je w wersji szkolnej, nie zastanawiając się nad jakąkolwiek optymalizacją. Następnie spróbuj zmienić organizację obliczeń tak by uzyskać poprawę wydajności. Na koniec porównaj swoje metody do dedykowanych funkcji z bibliotek NumPy i SciPy.

Numpy i SciPy zawierają dedykowane funkcje do rozwiązywania konkretnych problemów. Są one w miarę możliwości zoptymalizowane i wykorzystują różne przekształecenia oraz charakterystykę obiektów, na których pracują. Dzięki temu są one szybsze od autorskich implementacji.

In [12]:
import numpy as np
import time


def add_vectors(v1, v2):
    if len(v1) == len(v2):
        start = time.time()
        for i in range(len(v1)):
            v1[i] += v2[i]
        end = time.time()
        return v1, end - start
    else:
        print("You shouldn't add vectors of different lengths")


def cross_multiply_vectors(v1, v2):
    if isinstance(v1, np.ndarray):
        v1 = v1.tolist()
    if isinstance(v2, np.ndarray):
        v2 = v2.tolist()
    if len(v1) == len(v2):
        start = time.time()
        v3 = v1[1:] + v1[:-1]
        v4 = v2[1:] + v2[:-1]
        v5 = []
        for i in range(0, len(v3) - 1):
            v5 += [v3[i]*v4[i+1] - v3[i+1]*v4[i]]
        end = time.time()
        return v5, end - start
    else:
        return "You shouldn't multiply vectors of different lengths"


def multiply_matrices(m1, m2):
    if len(m1[0]) != len(m2):
        return "Incorrect dimensions"
    start = time.time()
    m3 = np.zeros((len(m1), len(m2[0])))
    for i in range(len(m1)):
        for j in range(len(m2[0])):
            for k in range(len(m2)):
                m3[i][j] += m1[i][k] * m2[k][j]
    end = time.time()
    return m3, start - end


def numpy_add_vectors(v1, v2):
    start = time.time()
    v3 = np.add(v1, v2)
    end = time.time()
    return v3, end - start


def numpy_cross_multiply_vectors(v1, v2):
    start = time.time()
    v3 = np.cross(v1, v2)
    end = time.time()
    return v3, end - start


def numpy_multiply_matrices(m1, m2):
    start = time.time()
    r = np.dot(m1, m2)
    end = time.time()
    return r, end - start


a = [[12, 7, 3],
     [4, 5, 6]]
b = [[5, 8, 1, 2],
     [6, 7, 3, 0],
     [4, 5, 9, 1]]
c = [1, 2, 3]
d = [3, 2, 1]

print("Numpy add two vectors:", numpy_add_vectors(c, d))
print("My add two vectors:", add_vectors(c, d), "\n")
print("Numpy cross multiply two vectors:", numpy_cross_multiply_vectors(c, d), "\n")
print("My cross multiply two vectors:", cross_multiply_vectors(c, d), "\n")
print("Numpy multiply matrices: \n", numpy_multiply_matrices(a, b)[0],
      "\n", numpy_multiply_matrices(a, b)[1])
print("My multiply matrices: \n", multiply_matrices(a, b)[0],
      "\n", multiply_matrices(a, b)[1])



Numpy add two vectors: (array([4, 4, 4]), 0.0)
My add two vectors: ([4, 4, 4], 0.0) 

Numpy cross multiply two vectors: (array([-4,  8, -4]), 0.0) 

My cross multiply two vectors: ([-4, 8, -4], 0.0) 

Numpy multiply matrices: 
 [[114 160  60  27]
 [ 74  97  73  14]] 
 0.0
My multiply matrices: 
 [[114. 160.  60.  27.]
 [ 74.  97.  73.  14.]] 
 0.0
